[package]
name = "bodhi-enclave"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.28", features = ["socket"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"

[features]
local-test = []

[[bin]]
name = "enclave"
path = "src/main.rs"
